from typing import Protocol

from app.schemas.chunks import Chunk, RetrievedChunk


class VectorStore(Protocol):
    def ensure_collection(self, dim: int) -> None: ...
    def upsert(self, items: list[tuple[Chunk, list[float]]]) -> None: ...
    def search(self, vector: list[float], top_k: int) -> list[RetrievedChunk]: ...
    def count(self) -> int: ...
